sudo: false
language: ruby
before_install:
  - npm install -g geojsonhint
cache: bundler
branches:
  only:
    - master
rvm:
  - 2.1
script:
  - bundle exec jekyll build
  - bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html --empty-alt-ignore --ignore-script-embeds
  - bash -e geojsonhint _data/chapters.json

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
