url: http://maptime.io
baseurl:
permalink: pretty
markdown: kramdown
paginate: 5
repo: maptime.github.io
github_org: maptime
maptime:
  chapter: Maptime HQ
  twitter: maptimehq
  #disqus: YOUR DISQUS USERNAME 

excerpt_separator: <!--more-->
exclude: [vendor]

gems:
  - jekyll-feed